### PR TITLE
Fix: Footer Responsiveness for all devices

### LINKED ISSUE #56: BUG: Make Footer Responsive
Participating in codepeak

### PR DESCRIPTION
**Pull request by AaadityaG**
Closes #56

## Fixing the responsiveness of footer section including font size..

Contact Us — Mozilla Firefox 28-12-2023 07_39_21 PM

Please consider this for 
## Codepeak

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hi, your changes lacks space and hover effects on the footer elements.

**Comment by AaadityaG** [comment]
Its done!


https://github.com/MonalikaPatnaik/SheEARNS/assets/114663382/6fe05bc8-af70-4d89-8332-0609be95a4bb

**Comment by MonalikaPatnaik** [comment]
Hi, the footer is not yet responsive. The subscribe button is out of the footer.
image

**Comment by AaadityaG** [comment]
It finaly done.. I think..

https://github.com/MonalikaPatnaik/SheEARNS/assets/114663382/1a6e0d42-50b2-4536-81ec-433cbf6f1755

**Pull request merged**
