### PR TITLE
fix: about page component

### LINKED ISSUE #29: Feat: About Page
**Describe the feature.**

The About Page is not ready...👇🏽

https://she-earns-xi.vercel.app/about

**Add Screenshots**

SheEARNS — Mozilla Firefox 18-12-2023 08_42_58 PM

### PR DESCRIPTION
**Pull request by AaadityaG**
Close #29 

SheEARNS — Mozilla Firefox 24-12-2023 12_27_50 PM

### CODE REVIEW

**Comment by AaadityaG** [comment]
@MonalikaPatnaik  Its done, please considr for codepeak points

**Comment by MonalikaPatnaik** [comment]
Thankyou..looking good to me. Just pull the changes in your branch by using `git pull` and add the About element in the navbar here.
image

**Comment by AaadityaG** [comment]
Should I raise a new PR?

**Comment by MonalikaPatnaik** [comment]
> Should I raise a new PR?

No, push commits to this PR only.

**Comment by AaadityaG** [comment]
How can I pull _main_ branch uptodate with _aboutpage_  branch

**Comment by AaadityaG** [comment]
Ok I got it
Also Small Update I did like below 


SheEARNS — Mozilla Firefox 24-12-2023 01_26_35 PM


Isn't it more appealing

**Comment by MonalikaPatnaik** [comment]
first switch to your feature branch by using `git checkout aboutpage` command in your terminal.
then try using the command `git pull origin main` to pull the changes.

**Comment by MonalikaPatnaik** [comment]
> Ok I got it Also Small Update I did like below
> 
> SheEARNS — Mozilla Firefox 24-12-2023 01_26_35 PM
> 
> Isn't it more appealing

yes. looking good <3

**Comment by AaadityaG** [comment]
Finally Its done... I think..😅

**Pull request merged**
