### PR TITLE
feat: Button Added

### LINKED ISSUE #9: Feat: Add a one-click  back to top button for website
**Describe the feature.**

I wish to add a one -click back to top button. In case there are too many stores, it's a hassle to scroll up
**Add Screenshots**

### PR DESCRIPTION
**Pull request by vikramnagwal**
closes #9 

I have added a Back to Top button in the Home Page section. 

Screenshot:
.
image

### CODE REVIEW

**Comment by vikramnagwal** [comment]
Hello, Would you be available for some discussion related to the project?

**Comment by MonalikaPatnaik** [comment]
Hi, pls don't work on the issues which are not assigned to you. If the assigned person can't solve the issue, then only you can take it up.
Thanks!

**Comment by vikramnagwal** [comment]
Okay, can we discuss the project, please? It's important.
I have sent you a message on Twitter.

**Comment by MonalikaPatnaik** [comment]
> Okay, can we discuss the project, please? It's important. I have sent you a message on Twitter.

Yes, sure :)

**Pull request closed without merging**
