### PR TITLE
fixed UI,validation,stories card size bugs

### LINKED ISSUE #60: Style: Fixing contact page
Improper style for contact page

Changes i will make:
* make proper contact page 

Screenshot (156)

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
Closes #60 #61 #62 #63 

# Changes made :
* proper contact page with border,shadow 
* applied validations to contact form
* proper create strore page with proper UI
* applied validations to create store forms
* fixed stories sizes were not similar with each other

Screenshot (159)
Screenshot (160)
Screenshot (161)

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
@MonalikaPatnaik , Could you check this pr please

**Comment by MonalikaPatnaik** [comment]
Hi, could you please change the ui of the forms back to the previous ones like in this https://github.com/MonalikaPatnaik/SheEARNS/pull/4

**Comment by Yash-Ainapure** [comment]
> Hi, could you please change the ui of the forms back to the previous ones like in this #4

Ok

**Comment by Yash-Ainapure** [comment]
Sorry due to time issues of codepeak event i could not change width of form as requested.but i have implemented other changes regarding display of form as you told to do.
Screenshot (162)
Screenshot (163)

@MonalikaPatnaik
 🥲
I have solved 4 issues #61  #62 #63 and #64
Could you please review it. and give points accordingly. with the issue creation points before the event closes.

**Pull request merged**
