### PR TITLE
Made User Profile Page with all functionalities

### PR DESCRIPTION
**Pull request by PSS2134**
#36 
I have made the User Profile with all functionalities 
1. Designed profile Page
2. Implemented API for Image Uploading feature and Profile Editing
3. API for Shop Deletion
4. Search Bar functionality
5. fixed some bugs
6. Shows total shops owned in profile too

Screenshot 2023-12-27 100002
Screenshot 2023-12-27 100013

**Here is the video after these Changes** 
[SheEarns UserProfile.webm](https://github.com/MonalikaPatnaik/SheEARNS/assets/101321904/3b780068-8686-4863-a34b-687a2018bd87)
@MonalikaPatnaik

### CODE REVIEW

**Comment by PSS2134** [comment]
Also while creating the shop, I think there should be a field for description of shop (about the shop) which can be displayed

**Comment by MonalikaPatnaik** [comment]
> Also while creating the shop, I think there should be a field for description of shop (about the shop) which can be displayed

You can create a separate issue for that.
I tested your branch, for me, the account page is always loading and I can't see the user profile page. You can test it by clicking the view deployment option on this pr.
image

**Comment by PSS2134** [comment]
@MonalikaPatnaik I cannot see the deployment as it says Im not part of team. On my side its running fine, Is it because I have made a 3-4 new backend API and we need to re deploy the backend?

Screenshot 2023-12-27 180536

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik I cannot see the deployment as it says Im not part of team. On my side its running fine, Is it because I have made a 3-4 new backend API and we need to re deploy the backend?
> 
> Screenshot 2023-12-27 180536

For backend deployment, I have to merge this pr as the deployment is set to main branch of this repo

**Comment by MonalikaPatnaik** [comment]
Still not working:( can you check again on https://she-earns-xi.vercel.app/

**Comment by MonalikaPatnaik** [comment]
Your changes are visible..Thanks.
Awesome work 👌

**Comment by PSS2134** [comment]
> Your changes are visible..Thanks. Awesome work 👌

Also I had used my cloudinary endpoint, you need to replace the cloudinary endpoint with your endpoint
Screenshot 2023-12-27 201100

**Pull request merged**
