### PR TITLE
made preliminary edits to form and buttons

### PR DESCRIPTION
**Pull request by aindree-2005**
- Fixed colour scheme to be in website
- Fixed font of form

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hi, pls don't make Prs directly, create a PR to an issue only when it is assigned to you.

**Comment by aindree-2005** [comment]
> Hi, pls don't make Prs directly, create a PR to an issue only when it is assigned to you.

It is in association to issue #1  which was assigned to me

**Comment by MonalikaPatnaik** [comment]
> > Hi, pls don't make Prs directly, create a PR to an issue only when it is assigned to you.
> 
> It is in association to issue #1 which was assigned to me

Oh, I have added the PR template, always link your issue while making a PR.
Thanks!

**Comment by MonalikaPatnaik** [comment]
Quick Review: seems you have changed the color of the buttons only( you can change the color of the text to white when the button is not hovered). As per the issue, you can try changing the form structure like adding a border or background to it?

**Comment by aindree-2005** [comment]
> Quick Review: seems you have changed the color of the buttons only( you can change the color of the text to white when the button is not hovered). As per the issue, you can try changing the form structure like adding a border or background to it?

Oh ok got it!!

**Comment by aindree-2005** [comment]
fixes #1 
@MonalikaPatnaik made the form edits! 
Screenshot (223)
Screenshot (224)

**Comment by aindree-2005** [comment]
fixes #1  and #9

**Comment by MonalikaPatnaik** [comment]
Hi, looks good. just add the heading outside of the form and for the input fields, black border is not looking good. You can add a slight pink border to the input only when it is hovered otherwise not. 
Also, the fields are a bit wide, you can narrow down the fields or increase the padding from the left or right side. Try making the form responsive too.
Let me know of any issues.
Thankyou!

**Comment by aindree-2005** [comment]
> Hi, looks good. just add the heading outside of the form and for the input fields, black border is not looking good. You can add a slight pink border to the input only when it is hovered otherwise not. Also, the fields are a bit wide, you can narrow down the fields or increase the padding from the left or right side. Try making the form responsive too. Let me know of any issues. Thankyou!

Ok Making the PR in a jiffy. Got some touch ups left. So final summary of my work:
- Altered Button Designs (hover effect, colour change)
- Redesigned forms ( light violet background, added padding, made the borders appear on hover)
- Added Back to Top Button in Sync with form design.
This is the final list, fixes issue #1 , issue #9

**Comment by aindree-2005** [comment]
Screenshot (230)
Screenshot (231)
@MonalikaPatnaik added the changes you suggested!! fixes #1

**Comment by aindree-2005** [comment]
Screenshot (232)
Scroll 2 top button fixes #9

**Comment by MonalikaPatnaik** [comment]
Hi @aindree-2005, you have to make separate PR for each issue. So you have to make a different branch for scroll to top issue and make a separate PR from that branch.
Your changes for the form looks good, just remove the changes you have made for issue #9 and make a separate PR for that.

**Comment by aindree-2005** [comment]
@MonalikaPatnaik I made the updates in main branch. Finding it hard to separate out the features. But, I have created a separate PR for #9

**Pull request merged**
