### PR TITLE
new feature added

### PR DESCRIPTION
**Pull request by Sami3160**
issue #52
-A cards with banner like behavior are added
-Total 7 different and unique cards are added which rotates in loop
-Cards can be changed in both right-left direcction by both mouse and keyboard
-These are responsive and can change thir count based on screen width
-Cards theme also matches to webapp
-Cards are completely relatable to the webpage content
-The tecxt and title is also kept associated with the cards with meaningful contecxt
-As bonus animation is also added on load

Below is video :
https://github.com/MonalikaPatnaik/SheEARNS/assets/110652247/0a18de76-d338-462c-8f93-e81a721e3b2e

### CODE REVIEW

**Comment by MonalikaPatnaik** [comment]
Hi, vercel fails to deploy your changes, check them once
Screenshot_2023-12-27-23-34-28-89_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Sami3160** [comment]
> Hi, vercel fails to deploy your changes, check them once Screenshot_2023-12-27-23-34-28-89_40deb401b9ffe8e1df2f1cc5ba480b12

Okay, I'll check today, well it might be dependency related error

**Comment by Sami3160** [comment]
> Hi, vercel fails to deploy your changes, check them once Screenshot_2023-12-27-23-34-28-89_40deb401b9ffe8e1df2f1cc5ba480b12

hey @MonalikaPatnaik the changes are done, btw i wanted to ask are u the girl who come with harkirat on youtube??i saw someone like your face

**Comment by MonalikaPatnaik** [comment]
> > Hi, vercel fails to deploy your changes, check them once Screenshot_2023-12-27-23-34-28-89_40deb401b9ffe8e1df2f1cc5ba480b12
> 
> hey @MonalikaPatnaik the changes are done, btw i wanted to ask are u the girl who come with harkirat on youtube??i saw someone like your face

yes

**Comment by Sami3160** [comment]
> > > Hi, vercel fails to deploy your changes, check them once Screenshot_2023-12-27-23-34-28-89_40deb401b9ffe8e1df2f1cc5ba480b12
> > 
> > 
> > hey @MonalikaPatnaik the changes are done, btw i wanted to ask are u the girl who come with harkirat on youtube??i saw someone like your face
> 
> yes

dammmnn thats sooo cool!!! congrats btw!!

**Pull request merged**
